export const cFichaAlumno = {
  al_rut: "",
  al_dv: "",
  al_activo: 1,
  al_agno_matricula: 2025,
  al_nombres: "",
  al_apat: "",
  al_amat: "",
  al_canthnos: 0,
  al_cod_ense: 0,
  al_cod_grado: 0,
  al_cuidados: "",
  al_cur_repe: 2,
  al_descripcionvivecon: "",
  al_domicilio: "",
  al_enfermo: 2,
  al_evaluareligion: 0,
  al_f_nac: "",
  al_fecharetiro: "",
  al_fincorpora: "",
  al_genero: "M",
  al_hnosaca: 0,
  al_hnoscursos: "",
  al_id_alumno: 0,
  al_id_comuna: 13102,
  al_idapoderado: 0,
  al_idapoderadosupl: 0,
  al_idcurso: 1,
  al_idmadre: 0,
  al_idpadre: 0,
  al_idparentesco: 1,
  al_idparentescosupl: 0,
  al_idvivecon: 1,
  al_ingresogrupofamiliar: 0,
  al_letra: "",
  al_motivoretiro: "",
  al_nro_matricula: 0,
  al_nroentrehnos: 0,
  al_nrofamiliar: 0,
  al_procedencia: "",
  al_promedionota: 0.0,
  al_txtparentesco: "",
  al_txtparentescosupl: "",
  al_vivienda: 0,
  alcom_comuna: "",

  ap_rut: 0,
  ap_dv: "",
  ap_amat: "",
  ap_apat: "",
  ap_domicilio: "",
  ap_email: "",
  ap_emergencia: "",
  ap_fono1: "",
  ap_fono2: "",
  ap_id_comuna: 13102,
  ap_nombres: "",
  ap_parentesco: "",
  ap_sexo: "",
  apcom_comuna: "",

  apsu_rut: 0,
  apsu_dv: "",
  apsu_amat: "",
  apsu_apat: "",
  apsu_domicilio: "",
  apsu_email: "",
  apsu_emergencia: "",
  apsu_fono1: "",
  apsu_fono2: "",
  apsu_id_comuna: 13102,
  apsu_nombres: "",
  apsu_parentesco: "",
  apsu_sexo: "1",
  apsucom_comuna: "",

  c_nomcorto: "",

  madre_rut: 0,
  madre_amat: "",
  madre_apat: "",
  madre_dv: "",
  madre_estudios: "",
  madre_nombres: "",
  madre_ocupacion: "",

  padre_rut: 0,
  padre_amat: "",
  padre_apat: "",
  padre_dv: "",
  padre_estudios: "",
  padre_nombres: "",
  padre_ocupacion: "",
  vivec_descripcion: "",
  open: false,
  error: "",
  abort: false,
  nuevo: false,
  datagrid: false,
  buscando: true,
  encontrado: false,
};

export const valAlumno = {
  al_rut: {
    value: null,
    ty: "n", // tipo de dato: cadena de caracteres
    num: true, // ¿es numérico?
    nn: true, // ¿es no nulo?
    ml: 10, // longitud máxima
  },

  al_nombres: {
    value: null,
    ty: "c", // tipo de dato: cadena de caracteres
    num: false, // ¿es numérico?
    nn: true, // ¿es no nulo?
    ml: 80, // longitud máxima
  },
  al_amat: {
    value: null,
    ty: "c",
    num: false,
    nn: true,
    ml: 80,
  },
  al_apat: {
    value: null,
    ty: "c",
    num: false,
    nn: true,
    ml: 80,
  },
  al_f_nac: {
    value: null,
    ty: "d",
    num: false,
    nn: true,
    ml: 10,
  },
  al_domicilio: {
    value: null,
    ty: "c",
    num: false,
    nn: true,
    ml: 200,
  },
  al_canthnos: {
    value: null,
    ty: "n",
    num: false,
    nn: false,
    ml: 1,
  },
  al_cuidados: {
    value: null,
    ty: "c",
    num: false,
    nn: false,
    ml: 300,
  },
  al_cur_repe: {
    value: null,
    ty: "n",
    num: false,
    nn: false,
    ml: 1,
  },
  al_enfermo: {
    value: null,
    ty: "n",
    num: false,
    nn: false,
    ml: 1,
  },
  al_genero: {
    value: null,
    ty: "n",
    num: false,
    nn: true,
    ml: 1,
  },
  al_hnosaca: {
    value: null,
    ty: "n",
    num: false,
    nn: false,
    ml: 0,
  },
  al_hnoscursos: {
    value: null,
    ty: "d",
    num: true,
    nn: false,
    ml: 0,
  },
  al_nroentrehnos: {
    value: null,
    ty: "n",
    num: false,
    nn: false,
    ml: 0,
  },
  ma_cole_origen: {
    value: null,
    ty: "c",
    num: false,
    nn: true,
    ml: 200,
  },
  ma_promedionota: {
    value: null,
    ty: "n",
    num: true,
    nn: false,
    ml: 0,
  },
  ma_descripcionviveconotros: {
    value: null,
    ty: "c",
    num: false,
    nn: false,
    ml: 100,
  },
};

export const cFichaAlumnoOrdenada = [
  "al_rut",
  "al_dv",
  "al_nombres",
  "al_apat",
  "al_amat",
  "al_idcurso",
  "al_f_nac",
  "al_genero",
  "al_domicilio",
  "al_id_comuna",
  "al_procedencia",
  "al_promedionota",
  "al_cur_repe ",
  "al_idvivecon",
  "al_descripcionvivecon",
  "al_enfermo ",
  "al_cuidados",
  "al_canthnos",
  "al_nroentrehnos",
  "al_hnosaca",
  "al_hnoscursos",

  "ap_rut",
  "ap_dv",
  "ap_nombres",
  "ap_apat",
  "ap_amat",
  "al_idparentesco",
  "ap_fono1",
  "ap_fono2",
  "ap_emergencia",
  "ap_email",
  "ap_domicilio",
  "ap_id_comuna",

  "apsu_rut",
  "apsu_dv",
  "apsu_nombres",
  "apsu_apat",
  "apsu_amat",
  "al_idparentescosupl",
  "apsu_fono1",
  "apsu_fono2",
  "apsu_emergencia",
  "apsu_email",
  "apsu_domicilio",
  "apsu_id_comuna",

  "padre_dv ",
  "padre_rut",
  "padre_nombres",
  "padre_apat",
  "padre_amat",
  "padre_estudios ",
  "padre_ocupacion",

  "madre_dv ",
  "madre_rut",
  "madre_nombres",
  "madre_amat",
  "madre_apat",
  "madre_estudios ",
  "madre_ocupacion",

  "al_ingresogrupofamiliar",
  "al_vivienda",
  "al_evaluareligion",
];

export const dataResultado = {
  fRut: "",
  dv: "",
  result: 0,
  al_amat: "",
  al_apat: "",
  al_nombres: "",
  RutBuscar: "",
  GrbAlumno: 0,
  GrbApode: 0,
  GrabFamilia: 0,
  ApRut: "",
  ApDv: "",
  ApsuRut: "",
  ApsuDv: "",
  PadRut: "",
  PadDv: "",
  MadRut: "",
  MadDv: "",
  BuscaAp: 0,
  BuscaApSup: 0,
  BuscaPadre: 0,
  BuscaMadre: 0,
  swParentesco: 0
};
